RESULTS = data/Li01a.ce data/Li01a.ci data/Li01a.en data/Li01a.rr data/Li01a.tr\
	  data/Li02a.ce data/Li02a.ci data/Li02a.en data/Li02a.rr data/Li02a.tr\
	  Li01/Li01a_t00d0i1.rt Li01/Li01a_t00d0i1.sp \
	  Li01/Li01a_t00d0i2.rt Li01/Li01a_t00d0i2.sp \
	  Li01/Li01a_t01d0i1.rt Li01/Li01a_t01d0i1.sp \
	  Li01/Li01a_t01d0i2.rt Li01/Li01a_t01d0i2.sp \
	  Li02/Li02a_t00d0i1.rt Li02/Li02a_t00d0i1.sp \
	  Li02/Li02a_t00d0i2.rt Li02/Li02a_t00d0i2.sp \
	  Li02/Li02a_t01d0i1.rt Li02/Li02a_t01d0i1.sp \
	  Li02/Li02a_t01d0i2.rt Li02/Li02a_t01d0i2.sp

all:
	python li.py
	python spec.py


include ../Make.common
