RESULTS = data/Fe08a.ai data/Fe08a.ce data/Fe08a.ci data/Fe08a.en\
          data/Fe08a.rr data/Fe08a.tr\
          data/Fe09a.ai data/Fe09a.ce data/Fe09a.ci data/Fe09a.en\
          data/Fe09a.rr data/Fe09a.tr\
          data/Fe10a.ai data/Fe10a.ce data/Fe10a.ci data/Fe10a.en\
          data/Fe10a.rr data/Fe10a.tr\

all:
	python fe.py
	python spec.py

	
include ../Make.common
